LOCK TABLES `player` WRITE;

INSERT INTO `player` VALUES (2017,'Troicki Viktor','Serbia','ATP'),
(2018,'Pavlasek Adam','Czech Republic','ATP'),
(2019,'Halys Quentin','France','ATP'),
(2020,'Rubin Noah','USA','ATP'),
(2021,'Young Donald','USA','ATP'),
(2022,'Muller Gilles','Luxembourg','ATP'),
(2023,'O\'Connell Christopher','Australia','ATP'),
(2024,'Rublev Andrey','Russia','ATP'),
(2025,'Nishioka Yoshihito','Japan','ATP'),
(2026,'Cuevas Pablo','Uruguay','ATP'),
(2027,'Bautista-Agut Roberto','Spain','ATP'),
(2028,'Kyrgios Nick','Australia','ATP'),
(2029,'Darcis Steve','Belgium','ATP'),
(2030,'Brown Dustin','Germany','ATP'),
(2031,'Wawrinka Stan','Switzerland','ATP'),
(2032,'Jaziri Malek','Tunis','ATP'),
(2033,'Dimitrov Grigor','Bulgaria','ATP'),
(2034,'Sousa Joao','Portugal','ATP'),
(2035,'Almagro Nicolas','Spain','ATP'),
(2036,'Albot Radu','Moldavsko','ATP'),
(2037,'Berdych Tomas','Czech Republic','ATP'),
(2038,'Herbert Pierre-Hugues','France','ATP'),
(2039,'Monfils Gael','France','ATP'),
(2040,'Estrella Victor','Dominican Rep.','ATP'),
(2041,'Haase Robin','Netherlands','ATP'),
(2042,'Querrey Sam','USA','ATP'),
(2043,'Kravchuk Konstantin','Russia','ATP'),
(2044,'Bedene Aljaz','Great Britain','ATP'),
(2045,'Marchenko Ilya','Ukraine','ATP'),
(2046,'Klizan Martin','Slovakia','ATP'),
(2047,'Raonic Milos','Canada','ATP'),
(2048,'Mmoh Michael','USA','ATP'),
(2049,'Soeda Go','Japan','ATP'),
(2050,'Istomin Denis','Uzbekistan','ATP'),
(2051,'Robert Stephane','France','ATP'),
(2052,'Paire Benoit','France','ATP'),
(2053,'Fabbiano Thomas','Italy','ATP'),
(2054,'Simon Gilles','France','ATP'),
(2055,'Seppi Andreas','Italy','ATP'),
(2056,'Dzumhur Damir','Bosnia and Herzeg.','ATP'),
(2057,'Tomic Bernard','Australia','ATP'),
(2058,'Tiafoe Francis','USA','ATP'),
(2059,'Thiem Dominic','Austria','ATP'),
(2060,'Karlovic Ivo','Croatia','ATP'),
(2061,'Opelka Reilly','USA','ATP'),
(2062,'Monteiro Thiago Moura','Brazil','ATP'),
(2063,'Donaldson Jared','USA','ATP'),
(2064,'Chung Hyeon','South Korea','ATP'),
(2065,'Lorenzi Paolo','Italy','ATP'),
(2066,'Verdasco Fernando','Spain','ATP'),
(2067,'Fratangelo Bjorn','USA','ATP'),
(2068,'Carreno-Busta Pablo','Spain','ATP'),
(2069,'Kukushkin Mikhail','Kazakhstan','ATP'),
(2070,'Lacko Lukas','Slovakia','ATP'),
(2071,'Dolgopolov Aleksandr','Ukraine','ATP'),
(2072,'Fognini Fabio','Italy','ATP'),
(2073,'Edmund Kyle','Great Britain','ATP'),
(2074,'Duckworth James','Australia','ATP'),
(2075,'Lu Yen-hsun','Taipei (CHN)','ATP'),
(2076,'Stepanek Radek','Czech Republic','ATP'),
(2077,'Khachanov Karen','Russia','ATP'),
(2078,'Zverev Alexander','Germany','ATP'),
(2079,'Whittington Andrew','Australia','ATP'),
(2080,'Delbonis Federico','Argentina','ATP'),
(2081,'Janowicz Jerzy','Poland','ATP'),
(2082,'Tsonga Jo-Wilfried','France','ATP'),
(2083,'Murray Andy','Great Britain','ATP'),
(2084,'Zverev Mischa','Germany','ATP'),
(2085,'Coric Borna','Croatia','ATP'),
(2086,'Melzer Gerald','Austria','ATP'),
(2087,'Polansky Peter','Canada','ATP'),
(2088,'Bellucci Thomaz','Brazil','ATP'),
(2089,'Garcia-Lopez Guillermo','Spain','ATP'),
(2090,'Jasika Omar','Australia','ATP'),
(2091,'Melzer Jurgen','Austria','ATP'),
(2092,'Granollers-Pujol Marcel','Spain','ATP'),
(2093,'Nishikori Kei','Japan','ATP'),
(2094,'Pella Guido','Argentina','ATP'),
(2095,'Tursunov Dmitry','Russia','ATP'),
(2096,'Groth Samuel','Australia','ATP'),
(2097,'Thompson Jordan','Australia','ATP'),
(2098,'Gasquet Richard','France','ATP'),
(2099,'Dodig Ivan','Croatia','ATP'),
(2100,'Kuznetsov Andrey','Russia','ATP'),
(2101,'Bublik Alexander','Kazakhstan','ATP'),
(2102,'Olivo Renzo','Argentina','ATP'),
(2103,'Vesely Jiri','Czech Republic','ATP'),
(2104,'Vanni Luca','Italy','ATP'),
(2105,'Medvedev Daniil','Russia','ATP'),
(2106,'Berlocq Carlos','Argentina','ATP'),
(2107,'Schwartzman Diego Sebastian','Argentina','ATP'),
(2108,'Kohlschreiber Philipp','Germany','ATP'),
(2109,'Chardy Jeremy','France','ATP'),
(2110,'Evans Daniel','Great Britain','ATP'),
(2111,'Goffin David','Belgium','ATP'),
(2112,'Cilic Marin','Croatia','ATP'),
(2113,'Nadal Rafael','Spain','ATP'),
(2114,'Isner John','USA','ATP'),
(2115,'Bagnis Facundo','Argentina','ATP'),
(2116,'Elias Gastao','Portugal','ATP'),
(2117,'Federer Roger','Switzerland','ATP'),
(2118,'Escobedo Ernesto','USA','ATP'),
(2119,'Haas Tommy','Germany','ATP'),
(2120,'Mott Blake','Australia','ATP'),
(2121,'Ramos-Vinolas Albert','Spain','ATP'),
(2122,'Mahut Nicolas','France','ATP'),
(2123,'Giraldo Santiago','Colombia','ATP'),
(2124,'Lopez Feliciano','Spain','ATP'),
(2125,'Silva Dutra Rogerio','Brazil','ATP'),
(2126,'Fritz Taylor Harry','USA','ATP'),
(2127,'Lajovic Dusan','Serbia','ATP'),
(2128,'Zeballos Horacio','Argentina','ATP'),
(2129,'Baghdatis Marcos','Cyprus','ATP'),
(2130,'Mayer Florian','Germany','ATP'),
(2131,'Sela Dudi','Israel','ATP'),
(2132,'Bolt Alex','Australia','ATP'),
(2133,'Basilashvili Nikoloz','Georgia','ATP'),
(2134,'Djokovic Novak','Serbia','ATP'),
(2135,'Mannarino Adrian','France','ATP'),
(2136,'Sock Jack','USA','ATP'),
(2137,'Struff Jan-Lennard','Germany','ATP'),
(2138,'Mathieu Paul-Henri','France','ATP'),
(2139,'Johnson Steve','USA','ATP'),
(2140,'Pouille Lucas','France','ATP'),
(2141,'Harrison Ryan','USA','ATP'),
(2142,'De Minaur Alex','Australia','ATP'),
(2143,'Youzhny Mikhail','Russia','ATP'),
(2144,'Ferrer David','Spain','ATP'),
(2145,'Erakovic Marina','New Zealand','WTA'),
(2146,'Davis Lauren','USA','WTA'),
(2147,'Muguruza Blanco Garbine','Spain','WTA'),
(2148,'Makarova Ekaterina','Russia','WTA'),
(2149,'Parmentier Pauline','France','WTA'),
(2150,'Petkovic Andrea','Germany','WTA'),
(2151,'Hsieh Su-Wei','Taipei (CHN)','WTA'),
(2152,'Cepelova Jana','Slovakia','WTA'),
(2153,'Barthel Mona','Germany','WTA'),
(2154,'Kasatkina Darya','Russia','WTA'),
(2155,'Kozlova Kateryna','Ukraine','WTA'),
(2156,'Cornet Alize','France','WTA'),
(2157,'Witthoeft Carina','Germany','WTA'),
(2158,'Williams Venus','USA','WTA'),
(2159,'Vekic Donna','Croatia','WTA'),
(2160,'Zheng Saisai','China','WTA'),
(2161,'Pliskova Kristyna','Czech Republic','WTA'),
(2162,'Cibulkova Dominika','Slovakia','WTA'),
(2163,'Gibbs Nicole','USA','WTA'),
(2164,'Khromacheva Irina','Russia','WTA'),
(2165,'Niculescu Monica','Romania','WTA'),
(2166,'Aiava Destanee','Australia','WTA'),
(2167,'Chirico Louisa','USA','WTA'),
(2168,'Falconi Irina','USA','WTA'),
(2169,'Sevastova Anastasija','Latvia','WTA'),
(2170,'Cabrera Lizette','Australia','WTA'),
(2171,'Sasnovich Aliaksandra','Belarus','WTA'),
(2172,'Cirstea Sorana-Mihaela','Romania','WTA'),
(2173,'Pironkova Tsvetana','Bulgaria','WTA'),
(2174,'Vandeweghe Coco','USA','WTA'),
(2175,'Garcia Caroline','France','WTA'),
(2176,'Doi Misaki','Japan','WTA'),
(2177,'Bouchard Eugenie','Canada','WTA'),
(2178,'Ozaki Risa','Japan','WTA'),
(2179,'Siniakova Katerina','Czech Republic','WTA'),
(2180,'Rogers Shelby','USA','WTA'),
(2181,'Barty Ashleigh','Australia','WTA'),
(2182,'Safarova Lucie','Czech Republic','WTA'),
(2183,'Duan Ying-Ying','China','WTA'),
(2184,'Vesnina Elena','Russia','WTA'),
(2185,'Hozumi Eri','Japan','WTA'),
(2186,'Sorribes Tormo Sara','Spain','WTA'),
(2187,'Giorgi Camila','Italy','WTA'),
(2188,'Peng Shuai','China','WTA'),
(2189,'Kulichkova Elizaveta','Russia','WTA'),
(2190,'Begu Irina','Romania','WTA'),
(2191,'Konta Johanna','Great Britain','WTA'),
(2192,'Sakkari Maria','Greece','WTA'),
(2193,'Rodina Evgeniya','Russia','WTA'),
(2194,'Alexandrova Ekaterina','Russia','WTA'),
(2195,'Day Kayla','USA','WTA'),
(2196,'Kumkhum Luksika','Thailand','WTA'),
(2197,'Kerber Angelique','Germany','WTA'),
(2198,'McHale Christina','USA','WTA'),
(2199,'Pliskova Karolina','Czech Republic','WTA'),
(2200,'Goerges Julia','Germany','WTA'),
(2201,'Vinci Roberta','Italy','WTA'),
(2202,'Schiavone Francesca','Italy','WTA'),
(2203,'Han Xin-Yun','China','WTA'),
(2204,'Kucova Kristina','Slovakia','WTA'),
(2205,'Fourlis Jaimee','Australia','WTA'),
(2206,'Gavrilova Daria','Australia','WTA'),
(2207,'Buyukakcay Cagla','Turkey','WTA'),
(2208,'Errani Sara','Italy','WTA'),
(2209,'Broady Naomi','Great Britain','WTA'),
(2210,'Jankovic Jelena','Serbia','WTA'),
(2211,'Wozniacki Caroline','Denmark','WTA'),
(2212,'King Vania','USA','WTA'),
(2213,'Beck Annika','Germany','WTA'),
(2214,'Rodionova Arina','Australia','WTA'),
(2215,'Voskoboeva Galina','Kazakhstan','WTA'),
(2216,'Allertova Denisa','Czech Republic','WTA'),
(2217,'Brady Jennifer','USA','WTA'),
(2218,'Tig Patricia Maria','Romania','WTA'),
(2219,'Bacsinszky Timea','Switzerland','WTA'),
(2220,'Konjuh Ana','Croatia','WTA'),
(2221,'Williams Serena','USA','WTA'),
(2222,'Halep Simona','Romania','WTA'),
(2223,'Pavlyuchenkova Anastasia','Russia','WTA'),
(2224,'Wang Qiang','China','WTA'),
(2225,'Wickmayer Yanina','Belgium','WTA'),
(2226,'Hibino Nao','Japan','WTA'),
(2227,'Strycova Barbora','Czech Republic','WTA'),
(2228,'Riske Alison','USA','WTA'),
(2229,'Dodin Oceane','France','WTA'),
(2230,'Radwanska Agnieszka','Poland','WTA'),
(2231,'Bencic Belinda','Switzerland','WTA'),
(2232,'Zhang Shuai','China','WTA'),
(2233,'Stosur Samantha','Australia','WTA'),
(2234,'Vogele Stefanie','Switzerland','WTA'),
(2235,'Tsurenko Lesya','Ukraine','WTA'),
(2236,'Nara Kurumi','Japan','WTA'),
(2237,'Kontaveit Anett','Estonia','WTA'),
(2238,'Lucic Mirjana','Croatia','WTA'),
(2239,'Tatishvili Anna','USA','WTA'),
(2240,'Blinkova Anna','Russia','WTA'),
(2241,'Siegemund Laura','Germany','WTA'),
(2242,'Lepchenko Varvara','USA','WTA'),
(2243,'Kovinic Danka','Montenegro','WTA'),
(2244,'Ostapenko Jelena','Latvia','WTA'),
(2245,'Knapp Karin','Italy','WTA'),
(2246,'Bondarenko Katerina','Ukraine','WTA'),
(2247,'Putintseva Yulia','Kazakhstan','WTA'),
(2248,'Crawford Samantha','USA','WTA'),
(2249,'Puig Monica','Puerto Rico','WTA'),
(2250,'Watson Heather','Great Britain','WTA'),
(2251,'Boserup Julia','USA','WTA'),
(2252,'Duque-Marino Mariana','Colombia','WTA'),
(2253,'Minella Mandy','Luxembourg','WTA'),
(2254,'Golubic Viktorija','Switzerland','WTA'),
(2255,'Vikhlyantseva Natalia','Russia','WTA'),
(2256,'Bogdan Ana','Romania','WTA'),
(2257,'Svitolina Elina','Ukraine','WTA'),
(2258,'Osaka Naomi','Japan','WTA'),
(2259,'Georges Myrtille','France','WTA'),
(2260,'Arruabarrena-Vecino Lara','Spain','WTA'),
(2261,'Brengle Madison','USA','WTA'),
(2262,'Mladenovic Kristina','France','WTA'),
(2263,'Zhu Lin','China','WTA'),
(2264,'Babos Timea','Hungary','WTA'),
(2265,'Flipkens Kirsten','Belgium','WTA'),
(2266,'Sramkova Rebecca','Slovakia','WTA'),
(2267,'Kuznetsova Svetlana','Russia','WTA'),
(2268,'Shvedova Yaroslava','Kazakhstan','WTA'),
(2269,'Zanevska Maryna','Belgium','WTA'),
(2270,'Suarez-Navarro Carla','Spain','WTA'),
(2271,'Linette Magda','Poland','WTA'),
(2272,'Bertens Kiki','Netherlands','WTA'),
(2273,'Gabashvili Teimuraz','Russia','ATP'),
(2274,'Bolelli Simone','Italy','ATP'),
(2275,'Tsitsipas Stefanos','Greece','ATP'),
(2276,'Stakhovsky Sergiy','Ukraine','ATP'),
(2277,'Tipsarevic Janko','Serbia','ATP'),
(2278,'Copil Marius','Romania','ATP'),
(2279,'Napolitano Stefano','Italy','ATP'),
(2280,'Kokkinakis Thanasi','Australia','ATP'),
(2281,'Berankis Ricardas','Lithuania','ATP'),
(2282,'Kovalik Jozef','Slovakia','ATP'),
(2283,'Muller Alexandre','France','ATP'),
(2284,'Gulbis Ernests','Latvia','ATP'),
(2285,'Sandgren Tennys','USA','ATP'),
(2286,'Daniel Taro','Japan','ATP'),
(2287,'Lokoli Laurent','France','ATP'),
(2288,'Bourgue Mathias','France','ATP'),
(2289,'Benneteau Julien','France','ATP'),
(2290,'Donskoy Evgeny','Russia','ATP'),
(2291,'Hamou Maxime','France','ATP'),
(2292,'Jarry Nicolas','Chile','ATP'),
(2293,'Anderson Kevin','RSA','ATP'),
(2294,'Bonzi Benjamin','France','ATP'),
(2295,'Robredo Tommy','Spain','ATP'),
(2296,'Del Potro Juan-Martin','Argentina','ATP'),
(2297,'De Greef Arthur','Belgium','ATP'),
(2298,'Millman John','Australia','ATP'),
(2299,'Sugita Yuichi','Japan','ATP'),
(2300,'Trungelliti Marco','Argentina','ATP'),
(2301,'Kicker Nicolas','Argentina','ATP'),
(2302,'Anisimova Amanda','USA','WTA'),
(2303,'Townsend Taylor','USA','WTA'),
(2304,'Mattek Bethanie','USA','WTA'),
(2305,'Andrianjafitrimo Tessah','France','WTA'),
(2306,'Bellis Catherine Cartan','USA','WTA'),
(2307,'Haddad Maia Beatriz','Brazil','WTA'),
(2308,'Hogenkamp Richel','Netherlands','WTA'),
(2309,'Kato Miyu','Japan','WTA'),
(2310,'Kvitova Petra','Czech Republic','WTA'),
(2311,'Maria Tatiana','Germany','WTA'),
(2312,'Cepede Veronica','Paraguay','WTA'),
(2313,'Hesse Amandine','France','WTA'),
(2314,'Tomljanovic Ajla','Croatia','WTA'),
(2315,'Lemoine Quirine','Netherlands','WTA'),
(2316,'Van Uytvanck Alison','Belgium','WTA'),
(2317,'Jabeur Ons','Tunis','WTA'),
(2318,'Abanda Francoise','Canada','WTA'),
(2319,'Lim Alize','France','WTA'),
(2320,'Mertens Elise','Belgium','WTA'),
(2321,'Keys Madison','USA','WTA'),
(2322,'Larsson Johanna','Sweden','WTA'),
(2323,'Ferro Fiona','France','WTA'),
(2324,'Vondrousova Marketa','Czech Republic','WTA'),
(2325,'Paquet Chloe','France','WTA'),
(2326,'Rybarikova Magdalena','Slovakia','WTA'),
(2327,'Martic Petra','Croatia','WTA'),
(2328,'Bemelmans Ruben','Belgium','ATP'),
(2329,'Haider-Maurer Andreas','Austria','ATP'),
(2330,'Shapovalov Denis','Canada','ATP'),
(2331,'Gojowczyk Peter','Germany','ATP'),
(2332,'Garin Christian','Chile','ATP'),
(2333,'Travaglia Stefano','Italy','ATP'),
(2334,'Laaksonen Henri','Switzerland','ATP'),
(2335,'Gombos Norbert','Slovakia','ATP'),
(2336,'Cecchinato Marco','Italy','ATP'),
(2337,'Rosol Lukas','Czech Republic','ATP'),
(2338,'Brands Daniel','Germany','ATP'),
(2339,'Ward Alexander','Great Britain','ATP'),
(2340,'Norrie Cameron','Great Britain','ATP'),
(2341,'Ofner Sebastian','Austria','ATP'),
(2342,'Ward James','Great Britain','ATP'),
(2343,'Klein Brydan','Great Britain','ATP'),
(2344,'Pospisil Vasek','Canada','ATP'),
(2345,'Fucsovics Marton','Hungary','ATP'),
(2346,'Lisicki Sabine','Germany','WTA'),
(2347,'Diyas Zarina','Kazakhstan','WTA'),
(2348,'Hercog Polona','Slovenia','WTA'),
(2349,'Robson Laura','Great Britain','WTA'),
(2350,'Stephens Sloane A.','USA','WTA'),
(2351,'Potapova Anastasia','Russia','WTA'),
(2352,'Chang Kai-Chen','Taipei (CHN)','WTA'),
(2353,'Boulter Katie','Great Britain','WTA'),
(2354,'Andreescu Bianca Vanessa','Canada','WTA'),
(2355,'Sabalenka Aryna','Belarus','WTA'),
(2356,'Azarenka Viktoria','Belarus','WTA');

UNLOCK TABLES;
